/* Generated by scripts/forms-pull.mjs. Do not edit.
   The forms as they were published when the copy that runs from a folder was
   built — it has no server to ask, so it carries them.

   Committed EMPTY, and filled only by `npm run offline`, which puts it back
   afterwards. Every use of what is below sits behind `__OFFLINE__`, so the
   site that runs from a server never reads a byte of it — it fetches what is
   published and keeps it in the browser. */
export const PACKED_AT = "";
export const PACKED = {};
